### ISSUE TITLE
Suggestion: random day in the future or past

### ISSUE THREAD

**Issue by tobyink** [tupinek/Random-Day#2]
It would be useful to have two subclasses:

* Random::Day::InTheFuture
* Random::Day::InThePast

Which act like Random::Day, but will always provide a day in the future/past.

**Comment by michal-josef-spacek** [comment]
@tobyink ok, interesting. Thank you for the idea.

**Comment by michal-josef-spacek** [comment]
@tobyink Implemented in [0.13](https://github.com/michal-josef-spacek/Random-Day/releases/tag/0.13)
